version: "3.9"

services:
  backend:
    image: ghcr.io/dev-sam17/samflix-backend:${BACKEND_TAG:-latest}
    container_name: samflix-backend-monorepo
    network_mode: "host"
    env_file:
      - .env.production
    dns:
    # cloudfare dns to access tmdb api 
      - 1.1.1.1
      - 1.0.0.1
    volumes:
    # add your media paths here
    restart: unless-stopped
